const iconCatalog = [
    // --- LUCIDE ---
    "lucide:home", "lucide:search", "lucide:settings", "lucide:user", "lucide:users",
    "lucide:heart", "lucide:star", "lucide:trash-2", "lucide:copy", "lucide:download",
    "lucide:upload", "lucide:check", "lucide:x", "lucide:menu", "lucide:calendar",
    "lucide:clock", "lucide:map-pin", "lucide:phone", "lucide:monitor", "lucide:camera",
    "lucide:wifi", "lucide:shield", "lucide:shopping-cart", "lucide:gift", "lucide:alert-circle",
    "lucide:chevron-down", "lucide:chevron-up", "lucide:chevron-left", "lucide:chevron-right",
    "lucide:plus", "lucide:minus", "lucide:filter", "lucide:grid", "lucide:list",
    "lucide:maximize", "lucide:minimize", "lucide:expand", "lucide:more-horizontal",
    "lucide:more-vertical", "lucide:eye", "lucide:eye-off", "lucide:info", "lucide:help-circle",
    "lucide:file", "lucide:file-text", "lucide:file-code", "lucide:file-image", "lucide:folder",
    "lucide:folder-open", "lucide:archive", "lucide:save", "lucide:clipboard", "lucide:log-in",
    "lucide:log-out", "lucide:user-plus", "lucide:user-x", "lucide:calendar-days", "lucide:clock-3",
    "lucide:watch", "lucide:timer", "lucide:hourglass", "lucide:droplet", "lucide:flame",
    "lucide:zap", "lucide:rocket", "lucide:code", "lucide:terminal", "lucide:database",
    "lucide:cloud", "lucide:cloud-download", "lucide:cloud-upload", "lucide:bluetooth", "lucide:usb",
    "lucide:github", "lucide:git-branch", "lucide:git-commit", "lucide:git-merge", "lucide:git-pull-request",
    "lucide:lock", "lucide:unlock", "lucide:key", "lucide:fingerprint", "lucide:shield-check",
    "lucide:edit", "lucide:pencil", "lucide:eraser", "lucide:scissors", "lucide:paintbrush",
    "lucide:palette", "lucide:crop", "lucide:rotate-cw", "lucide:rotate-ccw", "lucide:move",
    "lucide:arrow-up", "lucide:arrow-down", "lucide:arrow-left", "lucide:arrow-right",
    "lucide:arrow-up-right", "lucide:arrow-down-left", "lucide:corner-up-left", "lucide:corner-up-right",
    "lucide:corner-down-left", "lucide:corner-down-right", "lucide:refresh-cw",
    "lucide:mail", "lucide:inbox", "lucide:send", "lucide:message-circle", "lucide:message-square",
    "lucide:at-sign", "lucide:hash", "lucide:share-2", "lucide:link", "lucide:external-link",
    "lucide:bell", "lucide:bell-off", "lucide:volume-2", "lucide:volume-x", "lucide:volume-1",
    "lucide:mic", "lucide:mic-off", "lucide:video", "lucide:video-off", "lucide:play",
    "lucide:pause", "lucide:stop-circle", "lucide:skip-forward", "lucide:skip-back", "lucide:repeat",
    "lucide:shuffle", "lucide:fast-forward", "lucide:rewind", "lucide:music", "lucide:headphones",
    "lucide:radio", "lucide:podcast", "lucide:image", "lucide:film", "lucide:aperture",
    "lucide:sliders-horizontal", "lucide:sliders-vertical", "lucide:toggle-left", "lucide:toggle-right",
    "lucide:sun", "lucide:moon", "lucide:cloud-sun", "lucide:cloud-moon", "lucide:cloud-rain",
    "lucide:cloud-snow", "lucide:cloud-lightning", "lucide:wind", "lucide:umbrella", "lucide:snowflake",
    "lucide:coffee", "lucide:cup-soda", "lucide:utensils", "lucide:apple", "lucide:cherry",
    "lucide:grape", "lucide:banana", "lucide:carrot", "lucide:beef",
    "lucide:fish", "lucide:egg", "lucide:cake", "lucide:ice-cream", "lucide:candy",
    "lucide:plane", "lucide:train", "lucide:bus", "lucide:car", "lucide:bike",
    "lucide:ship", "lucide:anchor", "lucide:compass", "lucide:map", "lucide:globe",
    "lucide:flag", "lucide:trophy", "lucide:medal", "lucide:award", "lucide:crown",
    "lucide:gem", "lucide:diamond", "lucide:circle", "lucide:square", "lucide:triangle",
    "lucide:hexagon", "lucide:octagon", "lucide:pentagon", "lucide:box", "lucide:package",
    "lucide:shopping-bag", "lucide:credit-card", "lucide:wallet", "lucide:banknote", "lucide:coins",
    "lucide:trending-up", "lucide:trending-down", "lucide:bar-chart", "lucide:pie-chart", "lucide:line-chart",
    "lucide:activity", "lucide:heart-pulse", "lucide:thermometer", "lucide:scale",
    
    // --- TABLER ---
    "tabler:home", "tabler:search", "tabler:settings", "tabler:user", "tabler:heart",
    "tabler:star", "tabler:trash", "tabler:copy", "tabler:download", "tabler:upload",
    "tabler:check", "tabler:x", "tabler:menu-2", "tabler:calendar", "tabler:clock",
    "tabler:map-pin", "tabler:phone", "tabler:device-laptop", "tabler:camera", "tabler:wifi",
    "tabler:shield", "tabler:shopping-cart", "tabler:gift", "tabler:alert-circle", "tabler:file-text",
    "tabler:arrow-left", "tabler:arrow-right", "tabler:arrow-up", "tabler:arrow-down",
    "tabler:arrow-back-up", "tabler:arrow-forward-up", "tabler:external-link", "tabler:link",
    "tabler:anchor", "tabler:compass", "tabler:map", "tabler:map-2", "tabler:navigation",
    "tabler:globe", "tabler:chevron-down", "tabler:chevron-up", "tabler:chevron-left", "tabler:chevron-right",
    "tabler:corner-down-left", "tabler:corner-down-right", "tabler:corner-up-left", "tabler:corner-up-right",
    "tabler:edit", "tabler:pencil", "tabler:eraser", "tabler:scissors", "tabler:paint",
    "tabler:palette", "tabler:brush", "tabler:vector", "tabler:crop", "tabler:rotate",
    "tabler:code", "tabler:terminal", "tabler:cpu", "tabler:device-mobile", "tabler:device-tablet",
    "tabler:server", "tabler:database", "tabler:cloud", "tabler:cloud-download", "tabler:cloud-upload",
    "tabler:bluetooth", "tabler:usb", "tabler:brand-github", "tabler:brand-git",
    "tabler:lock", "tabler:lock-open", "tabler:shield-check", "tabler:shield-x",
    "tabler:key", "tabler:fingerprint", "tabler:mail", "tabler:mail-opened", "tabler:inbox",
    "tabler:send", "tabler:message", "tabler:message-2", "tabler:at", "tabler:hash",
    "tabler:share", "tabler:bell", "tabler:bell-ringing", "tabler:bell-off", "tabler:volume",
    "tabler:volume-2", "tabler:volume-3", "tabler:player-play", "tabler:player-pause", "tabler:player-stop",
    "tabler:player-skip-forward", "tabler:player-skip-back", "tabler:player-repeat", "tabler:player-shuffle",
    "tabler:microphone", "tabler:microphone-off", "tabler:video", "tabler:photo", "tabler:film",
    "tabler:music", "tabler:headphones", "tabler:radio", "tabler:sun", "tabler:moon",
    "tabler:cloud-rain", "tabler:cloud-snow", "tabler:cloud-storm", "tabler:wind", "tabler:umbrella",
    "tabler:coffee", "tabler:cup", "tabler:apple",
    "tabler:car", "tabler:bus", "tabler:train", "tabler:plane", "tabler:bike",
    "tabler:ship", "tabler:truck", "tabler:scooter", "tabler:flag", "tabler:trophy",
    "tabler:medal", "tabler:award", "tabler:crown", "tabler:diamond", "tabler:gem",
    "tabler:circle", "tabler:square", "tabler:triangle", "tabler:hexagon", "tabler:octagon",
    "tabler:box", "tabler:package", "tabler:shopping-bag", "tabler:credit-card", "tabler:wallet",
    "tabler:coin", "tabler:bank", "tabler:chart-bar", "tabler:chart-pie", "tabler:chart-line",
    "tabler:trending-up", "tabler:trending-down", "tabler:activity", "tabler:pulse", "tabler:heart-beat",
    "tabler:brand-facebook", "tabler:brand-twitter", "tabler:brand-instagram", "tabler:brand-linkedin", "tabler:brand-youtube",
    "tabler:brand-tiktok", "tabler:brand-snapchat", "tabler:brand-whatsapp", "tabler:brand-telegram", "tabler:brand-discord",
    
    // --- PHOSPHOR ---
    "ph:house", "ph:magnifying-glass", "ph:gear", "ph:user", "ph:heart",
    "ph:star", "ph:trash", "ph:copy", "ph:download-simple", "ph:upload-simple",
    "ph:check", "ph:x", "ph:list", "ph:calendar", "ph:clock",
    "ph:map-pin", "ph:phone", "ph:monitor", "ph:camera", "ph:wifi-high",
    "ph:shield", "ph:shopping-cart", "ph:gift", "ph:warning-circle", "ph:file-text",
    "ph:envelope", "ph:chat-circle", "ph:chat-teardrop", "ph:phone-call",
    "ph:paper-plane-tilt", "ph:inbox", "ph:bell", "ph:bell-ringing", "ph:at", "ph:hash",
    "ph:share-network", "ph:users-three", "ph:user-circle", "ph:hand-heart",
    "ph:shopping-bag", "ph:credit-card", "ph:wallet", "ph:currency-dollar",
    "ph:tag", "ph:percent", "ph:trend-up", "ph:trend-down", "ph:chart-bar", "ph:chart-pie",
    "ph:clock-clockwise", "ph:calendar-check", "ph:calendar-x", "ph:lightning", "ph:rocket",
    "ph:code", "ph:terminal", "ph:database", "ph:cloud", "ph:cloud-arrow-down",
    "ph:cloud-arrow-up", "ph:bluetooth", "ph:usb", "ph:github-logo", "ph:git-branch",
    "ph:lock", "ph:lock-open", "ph:key", "ph:fingerprint", "ph:shield-check",
    "ph:pencil", "ph:eraser", "ph:scissors", "ph:paint-brush", "ph:palette",
    "ph:crop", "ph:arrows-clockwise", "ph:arrows-counter-clockwise", "ph:cursor", "ph:hand",
    "ph:arrow-up", "ph:arrow-down", "ph:arrow-left", "ph:arrow-right", "ph:arrow-up-right",
    "ph:arrow-down-left", "ph:arrow-line-up", "ph:arrow-line-down", "ph:arrow-line-left", "ph:arrow-line-right",
    "ph:paperclip", "ph:link", "ph:link-break", "ph:link-simple", "ph:export",
    "ph:speaker-high", "ph:speaker-low", "ph:speaker-none", "ph:speaker-slash", "ph:microphone",
    "ph:microphone-slash", "ph:video-camera", "ph:video-camera-slash", "ph:play", "ph:pause",
    "ph:stop", "ph:skip-forward", "ph:skip-back", "ph:repeat", "ph:shuffle",
    "ph:fast-forward", "ph:rewind", "ph:music-notes", "ph:headphones", "ph:radio",
    "ph:podcast", "ph:image", "ph:film-strip", "ph:aperture", "ph:sliders",
    "ph:sun", "ph:moon", "ph:cloud-sun", "ph:cloud-moon", "ph:cloud-rain",
    "ph:cloud-snow", "ph:cloud-lightning", "ph:wind", "ph:umbrella", "ph:snowflake",
    "ph:coffee", "ph:cup","ph:apple",
    "ph:car", "ph:bus", "ph:train", "ph:airplane", "ph:bicycle",
    "ph:sailboat", "ph:truck", "ph:scooter", "ph:flag", "ph:trophy",
    "ph:medal", "ph:award", "ph:crown", "ph:diamond", "ph:gem",
    "ph:circle", "ph:square", "ph:triangle", "ph:hexagon", "ph:octagon",
    "ph:box", "ph:package", "ph:shopping-bag", "ph:credit-card", "ph:wallet",
    "ph:coin", "ph:bank", "ph:chart-bar", "ph:chart-pie", "ph:chart-line",
    "ph:activity", "ph:pulse", "ph:heart-half", "ph:thermometer", "ph:scale",
    "ph:facebook-logo", "ph:twitter-logo", "ph:instagram-logo", "ph:linkedin-logo", "ph:youtube-logo",
    "ph:tiktok-logo", "ph:snapchat-logo", "ph:whatsapp-logo", "ph:telegram-logo", "ph:discord-logo",
    
    // --- HEROICONS ---
    "heroicons:home", "heroicons:magnifying-glass", "heroicons:cog-6-tooth", "heroicons:user", "heroicons:heart",
    "heroicons:star", "heroicons:trash", "heroicons:document-duplicate", "heroicons:arrow-down-tray", "heroicons:arrow-up-tray",
    "heroicons:check", "heroicons:x-mark", "heroicons:bars-3", "heroicons:calendar", "heroicons:clock",
    "heroicons:map-pin", "heroicons:phone", "heroicons:computer-desktop", "heroicons:camera", "heroicons:wifi",
    "heroicons:shield-check", "heroicons:shopping-cart", "heroicons:gift", "heroicons:exclamation-circle", "heroicons:document-text",
    "heroicons:photo", "heroicons:video-camera", "heroicons:film",
    "heroicons:musical-note", "heroicons:microphone", "heroicons:microphone-slash",
    "heroicons:volume-up", "heroicons:volume-off", "heroicons:play", "heroicons:pause",
    "heroicons:stop", "heroicons:forward", "heroicons:backward", "heroicons:repeat", "heroicons:shuffle",
    "heroicons:sun", "heroicons:moon", "heroicons:cloud", "heroicons:cloud-rain",
    "heroicons:cloud-lightning", "heroicons:snowflake", "heroicons:wind",
    "heroicons:bug-ant", "heroicons:rocket-launch", "heroicons:light-bulb",
    "heroicons:code-bracket", "heroicons:command-line", "heroicons:cpu-chip", "heroicons:server", "heroicons:database",
    "heroicons:cloud-arrow-down", "heroicons:cloud-arrow-up", "heroicons:lock-closed", "heroicons:lock-open", "heroicons:key",
    "heroicons:pencil", "heroicons:eraser", "heroicons:scissors", "heroicons:paint-brush", "heroicons:swatch",
    "heroicons:arrow-up", "heroicons:arrow-down", "heroicons:arrow-left", "heroicons:arrow-right", "heroicons:arrow-up-right",
    "heroicons:arrow-down-left", "heroicons:chevron-up", "heroicons:chevron-down", "heroicons:chevron-left", "heroicons:chevron-right",
    "heroicons:envelope", "heroicons:inbox", "heroicons:paper-airplane", "heroicons:chat-bubble-left", "heroicons:chat-bubble-bottom-center",
    "heroicons:at-symbol", "heroicons:hashtag", "heroicons:share", "heroicons:link", "heroicons:arrow-top-right-on-square",
    "heroicons:bell", "heroicons:bell-slash", "heroicons:bell-alert", "heroicons:eye", "heroicons:eye-slash",
    "heroicons:information-circle", "heroicons:question-mark-circle", "heroicons:plus", "heroicons:minus", "heroicons:funnel",
    "heroicons:squares-2x2", "heroicons:list-bullet", "heroicons:arrows-pointing-out", "heroicons:arrows-pointing-in", "heroicons:ellipsis-horizontal",
    "heroicons:ellipsis-vertical", "heroicons:adjustments-horizontal", "heroicons:adjustments-vertical", "heroicons:flag", "heroicons:trophy",
    "heroicons:academic-cap", "heroicons:briefcase", "heroicons:building-office", "heroicons:building-storefront", "heroicons:banknotes",
    "heroicons:credit-card", "heroicons:currency-dollar", "heroicons:currency-euro", "heroicons:currency-pound", "heroicons:currency-yen",

    // --- REMIX ICON (ri) ---
    "ri:home-4-line", "ri:user-line", "ri:settings-3-line", "ri:search-line", "ri:heart-3-line",
    "ri:star-line", "ri:trash-3-line", "ri:edit-line", "ri:download-line", "ri:upload-line",
    "ri:check-line", "ri:close-line", "ri:menu-line", "ri:calendar-line", "ri:time-line",
    "ri:map-pin-line", "ri:phone-line", "ri:mail-line", "ri:message-3-line", "ri:notification-3-line",
    "ri:lock-line", "ri:key-line", "ri:shield-line", "ri:code-s-slash-line", "ri:terminal-box-line",
    "ri:database-2-line", "ri:cloud-line", "ri:wifi-line", "ri:camera-line", "ri:image-line",
    "ri:video-line", "ri:music-line", "ri:play-line", "ri:pause-line", "ri:volume-up-line",
    "ri:file-text-line", "ri:folder-line", "ri:share-line", "ri:link", "ri:arrow-left-line",
    "ri:arrow-right-line", "ri:refresh-line", "ri:sun-line", "ri:moon-line", "ri:car-line",
    "ri:plane-line", "ri:anchor-line", "ri:compass-3-line", "ri:flag-line", "ri:trophy-line",
    "ri:gift-line", "ri:shopping-cart-2-line", "ri:wallet-3-line", "ri:bank-card-line",
    "ri:pie-chart-2-line", "ri:bar-chart-box-line", "ri:dashboard-3-line", "ri:apps-line",
    "ri:filter-3-line", "ri:zoom-in-line", "ri:zoom-out-line", "ri:fullscreen-line",
    "ri:more-2-line", "ri:grid-line", "ri:list-unordered", "ri:align-left", "ri:bold",
    "ri:italic", "ri:paint-brush-line", "ri:palette-line", "ri:contrast-line", "ri:drop-line",
    "ri:fire-line", "ri:plant-line", "ri:recycle-line", "ri:earth-line", "ri:rocket-2-line",
    "ri:bug-line", "ri:robot-line", "ri:brain-line", "ri:heart-pulse-line", "ri:medicine-bottle-line",

    // --- MATERIAL DESIGN ICONS (mdi) ---
    "mdi:home", "mdi:magnify", "mdi:cog", "mdi:account", "mdi:account-group",
    "mdi:heart", "mdi:star", "mdi:delete", "mdi:content-copy", "mdi:download",
    "mdi:upload", "mdi:check", "mdi:close", "mdi:menu", "mdi:calendar",
    "mdi:clock-outline", "mdi:map-marker", "mdi:phone", "mdi:monitor", "mdi:camera",
    "mdi:wifi", "mdi:shield", "mdi:cart", "mdi:gift", "mdi:alert-circle",
    "mdi:chevron-down", "mdi:chevron-up", "mdi:chevron-left", "mdi:chevron-right",
    "mdi:plus", "mdi:minus", "mdi:filter", "mdi:view-grid", "mdi:view-list",
    "mdi:arrow-expand", "mdi:arrow-collapse", "mdi:eye", "mdi:eye-off", "mdi:information",
    "mdi:help-circle", "mdi:file", "mdi:file-document", "mdi:file-code", "mdi:folder",
    "mdi:folder-open", "mdi:archive", "mdi:content-save", "mdi:clipboard", "mdi:login",
    "mdi:logout", "mdi:account-plus", "mdi:account-remove", "mdi:watch", "mdi:timer",
    "mdi:hourglass", "mdi:water", "mdi:fire", "mdi:lightning-bolt", "mdi:rocket-launch",
    "mdi:code-tags", "mdi:console", "mdi:database", "mdi:cloud", "mdi:cloud-download",
    "mdi:cloud-upload", "mdi:bluetooth", "mdi:usb", "mdi:github", "mdi:git",
    "mdi:lock", "mdi:lock-open", "mdi:key", "mdi:fingerprint", "mdi:shield-check",
    "mdi:pencil", "mdi:eraser", "mdi:scissors", "mdi:brush", "mdi:palette",
    "mdi:crop", "mdi:rotate-right", "mdi:rotate-left", "mdi:cursor-default",
    "mdi:arrow-up", "mdi:arrow-down", "mdi:arrow-left", "mdi:arrow-right",
    "mdi:arrow-top-right", "mdi:arrow-bottom-left", "mdi:refresh", "mdi:email",
    "mdi:inbox", "mdi:send", "mdi:message", "mdi:message-text", "mdi:at",
    "mdi:hashtag", "mdi:share", "mdi:link", "mdi:link-variant", "mdi:bell",
    "mdi:bell-off", "mdi:volume-high", "mdi:volume-off", "mdi:microphone", "mdi:microphone-off",
    "mdi:video", "mdi:video-off", "mdi:play", "mdi:pause", "mdi:stop",
    "mdi:skip-next", "mdi:skip-previous", "mdi:repeat", "mdi:shuffle", "mdi:music",
    "mdi:headphones", "mdi:radio", "mdi:podcast", "mdi:image", "mdi:movie",
    "mdi:aperture", "mdi:tune", "mdi:toggle-switch", "mdi:weather-sunny", "mdi:weather-night",
    "mdi:weather-cloudy", "mdi:weather-rainy", "mdi:weather-lightning", "mdi:weather-windy", "mdi:umbrella",
    "mdi:coffee", "mdi:glass-cocktail", "mdi:food", "mdi:apple", "mdi:car",
    "mdi:bus", "mdi:train", "mdi:airplane", "mdi:bike", "mdi:ship",
    "mdi:anchor", "mdi:compass", "mdi:map", "mdi:earth", "mdi:flag",
    "mdi:trophy", "mdi:medal", "mdi:award", "mdi:crown", "mdi:gem",
    "mdi:diamond", "mdi:circle", "mdi:square", "mdi:triangle", "mdi:hexagon",
    "mdi:package", "mdi:shopping", "mdi:credit-card", "mdi:wallet", "mdi:cash",
    "mdi:coin", "mdi:bank", "mdi:chart-bar", "mdi:chart-pie", "mdi:chart-line",
    "mdi:trending-up", "mdi:trending-down", "mdi:activity", "mdi:heart-pulse", "mdi:thermometer",

    // --- FLUENT UI (fluent) - MICROSOFT ---
    "fluent:home-24-regular", "fluent:search-24-regular", "fluent:settings-24-regular",
    "fluent:person-24-regular", "fluent:people-24-regular", "fluent:heart-24-regular",
    "fluent:star-24-regular", "fluent:delete-24-regular", "fluent:copy-24-regular",
    "fluent:arrow-download-24-regular", "fluent:arrow-upload-24-regular", "fluent:checkmark-24-regular",
    "fluent:dismiss-24-regular", "fluent:line-horizontal-3-24-regular", "fluent:calendar-24-regular",
    "fluent:clock-24-regular", "fluent:location-24-regular", "fluent:phone-24-regular",
    "fluent:desktop-24-regular", "fluent:camera-24-regular", "fluent:wifi-1-24-regular",
    "fluent:shield-24-regular", "fluent:cart-24-regular", "fluent:gift-24-regular",
    "fluent:error-circle-24-regular", "fluent:document-24-regular", "fluent:folder-24-regular",
    "fluent:archive-24-regular", "fluent:save-24-regular", "fluent:clipboard-24-regular",
    "fluent:arrow-left-24-regular", "fluent:arrow-right-24-regular", "fluent:arrow-up-24-regular",
    "fluent:arrow-down-24-regular", "fluent:chevron-down-24-regular", "fluent:chevron-up-24-regular",
    "fluent:chevron-left-24-regular", "fluent:chevron-right-24-regular", "fluent:add-24-regular",
    "fluent:subtract-24-regular", "fluent:filter-24-regular", "fluent:grid-24-regular",
    "fluent:list-24-regular", "fluent:maximize-24-regular", "fluent:minimize-24-regular",
    "fluent:eye-24-regular", "fluent:eye-off-24-regular", "fluent:info-24-regular",
    "fluent:question-circle-24-regular", "fluent:edit-24-regular", "fluent:pen-24-regular",
    "fluent:eraser-24-regular", "fluent:scissors-24-regular", "fluent:paint-brush-24-regular",
    "fluent:color-24-regular", "fluent:crop-24-regular", "fluent:arrow-rotate-clockwise-24-regular",
    "fluent:arrow-rotate-counterclockwise-24-regular", "fluent:mail-24-regular", "fluent:inbox-24-regular",
    "fluent:send-24-regular", "fluent:chat-24-regular", "fluent:mention-24-regular",
    "fluent:hashtag-24-regular", "fluent:share-24-regular", "fluent:link-24-regular",
    "fluent:bell-24-regular", "fluent:bell-off-24-regular", "fluent:speaker-2-24-regular",
    "fluent:speaker-off-24-regular", "fluent:microphone-24-regular", "fluent:video-24-regular",
    "fluent:video-off-24-regular", "fluent:play-24-regular", "fluent:pause-24-regular",
    "fluent:stop-24-regular", "fluent:skip-forward-24-regular", "fluent:skip-back-24-regular",
    "fluent:repeat-1-24-regular", "fluent:shuffle-24-regular", "fluent:music-note-1-24-regular",
    "fluent:headphones-24-regular", "fluent:radio-button-24-regular", "fluent:podcast-24-regular",
    "fluent:image-24-regular", "fluent:filmstrip-24-regular", "fluent:options-24-regular",
    "fluent:toggle-left-24-regular", "fluent:toggle-right-24-regular", "fluent:weather-sunny-24-regular",
    "fluent:weather-moon-24-regular", "fluent:weather-cloudy-24-regular", "fluent:weather-rain-24-regular",
    "fluent:weather-snow-24-regular", "fluent:weather-thunderstorm-24-regular", "fluent:wind-24-regular",
    "fluent:umbrella-24-regular", "fluent:coffee-24-regular", "fluent:cup-24-regular",
    "fluent:food-24-regular", "fluent:car-24-regular", "fluent:bus-24-regular",
    "fluent:train-24-regular", "fluent:airplane-24-regular", "fluent:bike-24-regular",
    "fluent:ship-24-regular", "fluent:anchor-24-regular", "fluent:compass-24-regular",
    "fluent:map-24-regular", "fluent:globe-24-regular", "fluent:flag-24-regular",
    "fluent:trophy-24-regular", "fluent:medal-24-regular", "fluent:award-24-regular",
    "fluent:crown-24-regular", "fluent:diamond-24-regular", "fluent:circle-24-regular",
    "fluent:square-24-regular", "fluent:triangle-24-regular", "fluent:hexagon-24-regular",
    "fluent:box-24-regular", "fluent:package-24-regular", "fluent:shopping-bag-24-regular",
    "fluent:credit-card-24-regular", "fluent:wallet-24-regular", "fluent:coin-stack-24-regular",
    "fluent:bank-24-regular", "fluent:chart-bar-24-regular", "fluent:chart-pie-24-regular",
    "fluent:chart-line-24-regular", "fluent:trending-up-24-regular", "fluent:trending-down-24-regular",
    "fluent:activity-24-regular", "fluent:pulse-24-regular", "fluent:heart-pulse-24-regular",
    "fluent:thermometer-24-regular", "fluent:scale-24-regular", "fluent:lock-closed-24-regular",
    "fluent:lock-open-24-regular", "fluent:key-24-regular", "fluent:fingerprint-24-regular",
    "fluent:shield-checkmark-24-regular", "fluent:shield-dismiss-24-regular", "fluent:code-24-regular", "fluent:server-24-regular",
    "fluent:database-24-regular", "fluent:cloud-24-regular", "fluent:cloud-download-24-regular",
    "fluent:cloud-upload-24-regular", "fluent:bluetooth-24-regular", "fluent:usb-port-24-regular"
];
